spring:
  application:
    name: api-orchestrator
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/your_database_name
    username: your_username
    password: your_password
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  webflux:
    base-path: /

encryption:
  secret:
    key: YourSecretKey123  # Use a strong, randomly generated key in production

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.pensatocode.orchestrator: DEBUG
    org.springframework.security: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.reactive: DEBUG
    org.thymeleaf: TRACE
    org.springframework.boot.autoconfigure.thymeleaf: TRACE
