spring:
  application:
    name: api-orchestrator
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/your_database_name
    username: your_username
    password: your_password
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

encryption:
  secret:
    key: YourSecretKey123  # Use a strong, randomly generated key in production

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO
    com.example.orchestrator: DEBUG
